/**
 * `vinaya pr verify-evidence` — proves the published `AEG:EVIDENCE` region was
 * machine-generated, by regenerating it and comparing.
 *
 * **Deliberately a command, not a check.** `evidence-fresh` is registered in
 * `coreCheckRegistry()`, and `pr report` runs `vinaya check --all --diff-only`;
 * a check that regenerated the block would run the suite containing itself.
 * That recursion is exactly why `evidence-fresh` verifies Group A only and
 * leaves Group B attested. Living outside the registry is what lets this close
 * the gap without reintroducing the recursion.
 *
 * Reads the pull request body from the forge, regenerates a report against the
 * working tree, and compares. Run it from a checkout at the pull request's head
 * — comparing against a different tree reports a difference that is real but
 * uninteresting, so the head is printed for the reader to confirm.
 */

import { execFileSync } from 'node:child_process'
import { ScanContext, resolveAnchoredRegion } from '../checks/scan-context.js'
import { buildReport } from './pr-report.js'
import { compareEvidence, renderVerdict } from './pr-verify-evidence-logic.js'

function gh(args: string[]): string {
  return execFileSync('gh', args, { encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 })
}

/**
 * Refuses on a dirty worktree.
 *
 * Group B is regenerated by running `vinaya check --all --diff-only`, and
 * several of those checks are DIFF-SCOPED — they scan only the changed set.
 * An uncommitted or untracked file changes that scope, so a file that a clean
 * run would flag can silently fall out of it and the regeneration comes back
 * with fewer findings than the truth.
 *
 * That is not hypothetical: this exact contamination produced a FALSE MATCH on
 * a pull request whose published block was genuinely missing nine warnings, and
 * the false result was then published as a verified claim. A verifier that can
 * be quietly wrong in the reassuring direction is worse than none, so this
 * refuses rather than warns.
 */
function assertCleanWorktree(): void {
  // Run at the repo root, not the inherited cwd, so a subdirectory invocation
  // cannot narrow what is inspected.
  //
  // Deliberately WITHOUT `--ignored`, and the reason is worth recording because
  // a review round suggested adding it. Ignored paths cannot contaminate this:
  // Group B is regenerated by DIFF-scoped checks, which scope on `git diff`,
  // and `git diff` never reports an ignored file. What can contaminate it is a
  // modified or untracked file — which plain `--porcelain` does report, and
  // which is exactly what produced the false MATCH this guard exists for.
  // Adding `--ignored` would make the command refuse in every real checkout,
  // since `node_modules/` is ignored and always present after an install.
  const dirty = execFileSync('git', ['status', '--porcelain'], {
    encoding: 'utf8',
    cwd: repoRoot()
  }).trim()
  if (!dirty) return
  process.stderr.write(
    'pr verify-evidence: REFUSED — the worktree has uncommitted or untracked changes.\n' +
      'Group B is regenerated by diff-scoped checks, so local changes alter which files are scanned and can\n' +
      'produce a MATCH that a clean checkout would not. Verify from a clean checkout at this head instead.\n\n' +
      `${dirty}\n`
  )
  process.exit(2)
}

/**
 * Refuses when an environment override would steer the regeneration.
 *
 * `buildReport` resolves its merge-base from `process.env.BASE_SHA || 'origin/main'`
 * (`pr-report.ts`), so a `BASE_SHA` set to the published block's own base makes
 * a drifted comparison look like a shared-base one. That is the same
 * contamination class as a dirty worktree — an input this command does not
 * control silently changing what "a fresh run" means — and it is refused for
 * the same reason: a verifier that can be quietly steered toward MATCH is worse
 * than no verifier.
 */
function assertNoBaseOverride(): void {
  const override = process.env.BASE_SHA
  if (!override) return
  process.stderr.write(
    `pr verify-evidence: REFUSED — BASE_SHA is set (${override}).\n` +
      'The regeneration resolves its merge-base from that variable, so an override changes what a "fresh run"\n' +
      'means and can turn a drifted comparison into an apparently shared-base one. Unset it and re-run.\n'
  )
  process.exit(2)
}

/**
 * Refuses unless the process cwd IS the repository root.
 *
 * `buildReport()` spawns the gate suite with `cwd: process.cwd()`
 * (`pr-report.ts`'s `runRealGates`), and several gates resolve their scan root
 * from that cwd. Run from `apps/cli` there is no `aeg-root/` above them, so
 * `reader-resolvable-prose` collects nothing and `registry-gates` reports
 * itself dormant — an entire class of findings vanishes from the regenerated
 * Group B with no error, and a block with those findings deleted compares
 * MATCH.
 *
 * Two reviewers demonstrated it independently at the same head, on a clean
 * tree with the correct head and no `BASE_SHA`: a fabricated block reported
 * DIFFERS naming every deleted warning from the repo root, and MATCH from
 * `apps/cli`. Only the cwd changed.
 *
 * `assertCleanWorktree` already pins its own `git status` to `repoRoot()`,
 * with a comment saying a subdirectory invocation must not narrow what is
 * inspected. That reasoning was applied to the cheap half and not to the half
 * that decides the verdict. This closes it.
 *
 * Refusing rather than `chdir`-ing: a silent `chdir` would make the command
 * quietly do something other than what the caller asked, and every other guard
 * in this module refuses. Refusals cannot manufacture a MATCH — the failure
 * direction that matters here — whereas a wrong cwd can.
 */
function assertRepoRootCwd(): void {
  const root = repoRoot()
  const cwd = process.cwd()
  if (cwd === root) return
  process.stderr.write(
    `pr verify-evidence: REFUSED — run this from the repository root (${root}), not ${cwd}.\n` +
      'The regeneration inherits this working directory, and several gates resolve their scan root from it,\n' +
      'so a subdirectory silently narrows what the fresh run inspects and can report MATCH on a block that\n' +
      'omits real findings.\n'
  )
  process.exit(2)
}

function repoRoot(): string {
  return execFileSync('git', ['rev-parse', '--show-toplevel'], { encoding: 'utf8' }).trim()
}

export async function prVerifyEvidenceCommand(args: string[]): Promise<void> {
  // Positional only, and only the first one. `find(a => !a.startsWith('--'))`
  // would silently read the VALUE of a future `--flag value` pair as the pull
  // request number.
  const prRef = args[0] && !args[0].startsWith('-') ? args[0] : undefined
  if (!prRef) {
    process.stderr.write('Usage: vinaya pr verify-evidence <pr-number>\n')
    process.exit(2)
  }

  // Local guards FIRST, before anything touches the network.
  //
  // They ran after the `gh` call until now, which had two consequences. A user
  // in the wrong directory, or with an unreachable forge, got a generic
  // "could not read pull request" instead of the actionable local message that
  // names what to fix. And the guard test suite carried an undisclosed live
  // dependency: it claimed to be network-free and was not, passing only
  // because `gh` happened to work. Substituting a failing `gh` on PATH made
  // the network error fire first, which is how a reviewer found it.
  //
  // Cheap, deterministic, offline refusals belong ahead of an expensive one
  // that can fail for reasons the caller cannot act on.
  assertRepoRootCwd()
  assertCleanWorktree()
  assertNoBaseOverride()

  let body: string
  let forgeHead: string
  try {
    const view = JSON.parse(gh(['pr', 'view', prRef, '--json', 'body,headRefOid']))
    body = view.body ?? ''
    forgeHead = view.headRefOid ?? ''
  } catch (err) {
    process.stderr.write(`pr verify-evidence: could not read pull request #${prRef} — ${(err as Error).message}\n`)
    process.exit(1)
    return
  }

  // Head binding, not head attestation. Printing the local head to stderr and
  // trusting the reader to compare it is the same shape as the hand-pasted
  // claims this command exists to abolish — and a verdict redirected to a file
  // would carry no commit at all. A mismatch refuses.
  const localHead = execFileSync('git', ['rev-parse', 'HEAD'], { encoding: 'utf8' }).trim()
  if (!forgeHead) {
    // Fails CLOSED. An absent `headRefOid` means the binding could not be
    // established, and silently skipping the check would leave the verdict
    // unbound to any commit — the attestation-instead-of-binding shape this
    // command exists to remove.
    process.stderr.write(
      `pr verify-evidence: REFUSED — could not read #${prRef}'s head from the forge, so the verdict cannot be bound to a commit.\n`
    )
    process.exit(2)
  }
  if (forgeHead !== localHead) {
    process.stderr.write(
      `pr verify-evidence: REFUSED — this checkout is at ${localHead}, but #${prRef}'s head is ${forgeHead}.\n` +
        'Comparing against a different tree produces a difference that is real and uninteresting. Check out the head first.\n'
    )
    process.exit(2)
  }

  // Regenerating runs the real gates — the same run `pr report --write` would
  // have written. This is the whole point: the comparison is against a real
  // run, never against an assertion about one.
  const fresh = await buildReport()

  // Resolved through the SHARED resolver, never a raw `indexOf`. `pr-report.ts`
  // records why in its own splice path: a body that quotes a worked example of
  // its own anchor gets the quoted example picked instead of the real field —
  // "found live, in this task's own PR body". A raw scan here would have let
  // this command certify a decoy pair inside a fence or a `<details>` block
  // while `body-bare-digits` and `evidence-fresh` both read the real one.
  const resolved = resolveAnchoredRegion(ScanContext.from(body), 'EVIDENCE')
  const verdict = compareEvidence(
    resolved === null || resolved === 'hidden' ? resolved : { region: resolved.region },
    fresh.blockInner,
    repoRoot()
  )
  process.stdout.write(`${renderVerdict(verdict)}\n`)
  process.stdout.write(`  compared at head ${localHead}\n`)
  process.exit(verdict.status === 'match' ? 0 : 1)
}

import type { SurfaceExemption } from '../lib/surface-exemption'

export const SURFACE_EXEMPTIONS: Record<string, SurfaceExemption> = {
  'pr verify-evidence': { date: '2026-09-05', callsToday: 3, retiresVia: 'collectTokens' }
}
