import { createHash } from 'node:crypto'
import { ROLE_VALUES, type Header, type Host, type Provenance, type Role, type Subject } from './schema'

function isRole(value: string | undefined): value is Role {
  return value !== undefined && (ROLE_VALUES as readonly string[]).includes(value)
}

/** `null`/`''` reads as "no claim made" — never coerced into a guessed role identifier. */
function actorIdFromEnv(role: string | undefined): string | null {
  return role === undefined || role === '' ? null : role
}

function lineageFieldFromEnv(value: string | undefined): string | null {
  return value === undefined || value === '' ? null : value
}

function attemptFromEnv(value: string | undefined): number | null {
  if (value === undefined || value === '') return null
  const n = Number(value)
  return Number.isInteger(n) ? n : null
}

/**
 * Only a value the caller actually asserts becomes
 * `parent_attributed`/`self_reported` — `buildHeader` never upgrades trust
 * on its own (see `schema.ts`'s `ProvenanceSchema` doc). A `branchIssue`
 * deliberately does NOT count as an environment correlation: nothing about a
 * checked-out branch is one. An event whose `subject.issue` came from the
 * branch therefore reads `'unavailable'` EVEN WHEN the environment named a
 * role, because this one field describes the whole subject and there is no
 * way to say "the role was env-correlated, the issue was guessed" — reading
 * `'env_correlated'` beside a branch-guessed number would present a guess as
 * a correlation, and a process with `VINAYA_ROLE` set and `VINAYA_TASK`
 * absent or unparseable is exactly that shape. Under-claiming about the role
 * is the safe direction; over-claiming about the issue is not.
 */
function provenanceFor(input: Pick<HeaderInput, 'provenance' | 'env' | 'branchIssue'>): Provenance {
  if (input.provenance) return input.provenance
  if (issueFromTask(input.env.task) === null && (input.branchIssue ?? null) !== null) return 'unavailable'
  if (input.env.role || input.env.task) return 'env_correlated'
  return 'unavailable'
}

/** `VINAYA_TASK` parses to `subject.issue`; anything not a plain integer is `null` — never invented. `Number('')` is `0`, not `NaN`, so an empty string needs its own guard or it would parse as issue `0`. */
function issueFromTask(task: string | undefined): number | null {
  if (task === undefined || task === '') return null
  const n = Number(task)
  return Number.isInteger(n) ? n : null
}

function roundFromEnv(round: string | undefined): number | undefined {
  if (round === undefined || round === '') return undefined
  const n = Number(round)
  return Number.isInteger(n) ? n : undefined
}

/** `VINAYA_PR` parses to `subject.pr`; anything not a positive integer is absent — never invented. */
function prFromEnv(pr: string | undefined): number | undefined {
  if (pr === undefined || pr === '') return undefined
  const n = Number(pr)
  return Number.isInteger(n) && n > 0 ? n : undefined
}

/** Every value `buildHeader` needs, already read by the caller (the sink). Pure — no I/O here. */
export type HeaderInput = {
  now: Date
  runId: string
  seq: number
  repo: string | null
  vinaya: string
  doctrine: string
  host: Host
  hostname: string
  env: {
    role?: string
    task?: string
    round?: string
    /** `VINAYA_PR` — the pull request number once the loop has one; absent or not a positive integer reads as no number. */
    pr?: string
    run?: string
    attempt?: string
    parent?: string
    /** `VINAYA_WORK_REF`, `VINAYA_FLOW`, `VINAYA_FLOW_VERSION`, `VINAYA_RUNTIME`, `VINAYA_SOURCE` — the schema 3 identities a caller states; absent or empty reads `null` (`flow.id` reads `vinaya`). */
    workRef?: string
    flow?: string
    flowVersion?: string
    runtime?: string
    source?: string
  }
  /**
   * The Issue the caller's own checked-out branch names, for a process that
   * carries no `VINAYA_TASK` — `subject.issue`'s fallback, never its
   * override: an event that names its task in the environment keeps that
   * number. `null`/absent when the branch names no task or its Issue could
   * not be resolved, which stays `issue: null` rather than a guess. Read
   * by the caller (the sink, from `git`/`gh`); this module stays pure.
   */
  branchIssue?: number | null
  subject?: Partial<Subject>
  /** Stable per-event identity (O1) — generated by the caller (the sink), once per `log()` call, never here (this module stays free of non-deterministic output). */
  eventId: string
  /** Opaque per-process identifier (O1) — generated by the caller once per process, same lifetime as `runId`. */
  processId: string
  /** Set only by a caller that structurally knows the trust level (e.g. `dispatch.ts` asserting `'parent_attributed'` for its own dispatch-side events); absent, `provenanceFor` derives the honest default. */
  provenance?: Provenance
  /** Mirrors `review-input-manifest.ts`'s field set (camelCase, matching that module); absent fields read back `null`, never invented. */
  inputVersions?: {
    objectivesVersion?: string | null
    briefHash?: string | null
    rulingOrdinal?: number | null
    policyDigest?: string | null
  }
}

/**
 * Builds the header (`meta` + `subject`) from values already read by the
 * caller. No filesystem, network, or process access here — the purity
 * boundary (`apps/cli/specs/surface.md` "The rule"). `subject.role` and
 * `subject.issue` come only from `input.env`/`input.subject`, never
 * self-declared by whatever's building the rest of the event.
 *
 * Always builds `schema: 3` — `schema: 1` and `2` remain read-side
 * compatibility shapes only, for a line already on disk; `buildHeader` never
 * writes them.
 */
export function buildHeader(input: HeaderInput): Header {
  const role: Subject['role'] = isRole(input.env.role) ? input.env.role : 'unattributed'
  const round = roundFromEnv(input.env.round)
  const pr = prFromEnv(input.env.pr)
  const subject: Subject = {
    issue: issueFromTask(input.env.task) ?? input.branchIssue ?? null,
    role,
    ...(round !== undefined ? { round } : {}),
    ...(pr !== undefined ? { pr } : {}),
    ...(input.subject ?? {})
  }
  const issue = subject.issue
  return {
    meta: {
      schema: 3,
      ts: input.now.toISOString(),
      run_id: input.runId,
      seq: input.seq,
      repo: input.repo,
      vinaya: input.vinaya,
      doctrine: input.doctrine,
      host: input.host,
      machine: createHash('sha256').update(input.hostname).digest('hex'),
      event_id: input.eventId,
      process_id: input.processId,
      actor_id: actorIdFromEnv(input.env.role),
      lineage: {
        run: lineageFieldFromEnv(input.env.run),
        attempt: attemptFromEnv(input.env.attempt),
        parent: lineageFieldFromEnv(input.env.parent)
      },
      input_versions: {
        objectives_version: input.inputVersions?.objectivesVersion ?? null,
        brief_hash: input.inputVersions?.briefHash ?? null,
        ruling_ordinal: input.inputVersions?.rulingOrdinal ?? null,
        policy_digest: input.inputVersions?.policyDigest ?? null
      },
      provenance: provenanceFor(input),
      work: {
        // A stated reference wins; failing that the Issue number `subject.issue` already carries; never anything guessed.
        ref: lineageFieldFromEnv(input.env.workRef) ?? (issue === null ? null : String(issue)),
        repo: input.repo,
        change: null,
        revision: null
      },
      flow: {
        id: lineageFieldFromEnv(input.env.flow) ?? 'vinaya',
        version: lineageFieldFromEnv(input.env.flowVersion)
      },
      runtime: lineageFieldFromEnv(input.env.runtime),
      source: lineageFieldFromEnv(input.env.source)
    },
    subject
  }
}
