import { createHash } from 'node:crypto'
import { ROLE_VALUES, type Header, type Host, type Provenance, type Role, type Subject } from './schema'

function isRole(value: string | undefined): value is Role {
  return value !== undefined && (ROLE_VALUES as readonly string[]).includes(value)
}

/** `null`/`''` reads as "no claim made" — never coerced into a guessed role identifier. */
function actorIdFromEnv(role: string | undefined): string | null {
  return role === undefined || role === '' ? null : role
}

function lineageFieldFromEnv(value: string | undefined): string | null {
  return value === undefined || value === '' ? null : value
}

function attemptFromEnv(value: string | undefined): number | null {
  if (value === undefined || value === '') return null
  const n = Number(value)
  return Number.isInteger(n) ? n : null
}

/** Only a value the caller actually asserts becomes `parent_attributed`/`self_reported` — `buildHeader` never upgrades trust on its own (see `schema.ts`'s `ProvenanceSchema` doc). */
function provenanceFor(input: Pick<HeaderInput, 'provenance' | 'env'>): Provenance {
  if (input.provenance) return input.provenance
  if (input.env.role || input.env.task) return 'env_correlated'
  return 'unavailable'
}

/** `VINAYA_TASK` parses to `subject.issue`; anything not a plain integer is `null` — never invented. `Number('')` is `0`, not `NaN`, so an empty string needs its own guard or it would parse as issue `0`. */
function issueFromTask(task: string | undefined): number | null {
  if (task === undefined || task === '') return null
  const n = Number(task)
  return Number.isInteger(n) ? n : null
}

function roundFromEnv(round: string | undefined): number | undefined {
  if (round === undefined || round === '') return undefined
  const n = Number(round)
  return Number.isInteger(n) ? n : undefined
}

/** Every value `buildHeader` needs, already read by the caller (the sink). Pure — no I/O here. */
export type HeaderInput = {
  now: Date
  runId: string
  seq: number
  repo: string | null
  vinaya: string
  doctrine: string
  host: Host
  hostname: string
  env: { role?: string; task?: string; round?: string; run?: string; attempt?: string; parent?: string }
  subject?: Partial<Subject>
  /** Stable per-event identity (O1) — generated by the caller (the sink), once per `log()` call, never here (this module stays free of non-deterministic output). */
  eventId: string
  /** Opaque per-process identifier (O1) — generated by the caller once per process, same lifetime as `runId`. */
  processId: string
  /** Set only by a caller that structurally knows the trust level (e.g. `dispatch.ts` asserting `'parent_attributed'` for its own dispatch-side events); absent, `provenanceFor` derives the honest default. */
  provenance?: Provenance
  /** Mirrors `review-input-manifest.ts`'s field set (camelCase, matching that module); absent fields read back `null`, never invented. */
  inputVersions?: {
    objectivesVersion?: string | null
    briefHash?: string | null
    rulingOrdinal?: number | null
    policyDigest?: string | null
  }
}

/**
 * Builds the header (`meta` + `subject`) from values already read by the
 * caller. No filesystem, network, or process access here — the purity
 * boundary (`apps/cli/specs/surface.md` "The rule"). `subject.role` and
 * `subject.issue` come only from `input.env`/`input.subject`, never
 * self-declared by whatever's building the rest of the event.
 *
 * Always builds `schema: 2` (this task forward) — `schema: 1` remains a
 * read-side compatibility shape only, for a line already on disk before
 * this task; `buildHeader` never writes it.
 */
export function buildHeader(input: HeaderInput): Header {
  const role: Subject['role'] = isRole(input.env.role) ? input.env.role : 'unattributed'
  const round = roundFromEnv(input.env.round)
  const subject: Subject = {
    issue: issueFromTask(input.env.task),
    role,
    ...(round !== undefined ? { round } : {}),
    ...(input.subject ?? {})
  }
  return {
    meta: {
      schema: 2,
      ts: input.now.toISOString(),
      run_id: input.runId,
      seq: input.seq,
      repo: input.repo,
      vinaya: input.vinaya,
      doctrine: input.doctrine,
      host: input.host,
      machine: createHash('sha256').update(input.hostname).digest('hex'),
      event_id: input.eventId,
      process_id: input.processId,
      actor_id: actorIdFromEnv(input.env.role),
      lineage: {
        run: lineageFieldFromEnv(input.env.run),
        attempt: attemptFromEnv(input.env.attempt),
        parent: lineageFieldFromEnv(input.env.parent)
      },
      input_versions: {
        objectives_version: input.inputVersions?.objectivesVersion ?? null,
        brief_hash: input.inputVersions?.briefHash ?? null,
        ruling_ordinal: input.inputVersions?.rulingOrdinal ?? null,
        policy_digest: input.inputVersions?.policyDigest ?? null
      },
      provenance: provenanceFor(input)
    },
    subject
  }
}
